---
- name: Set accounts
  hosts: ~containerservice-adalab
  vars:
      uusername: "{{ ansible_ssh_user }}"
  become: true
  tasks:
      - name: Set {{ uusername }} password
        user:
            name: "{{ uusername }}"
            password: "{{ ansible_az_group | password_hash('sha512') }}"

      - name: Allow login with passwords
        lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PasswordAuthentication'
            line: 'PasswordAuthentication yes'
        notify: Restart sshd
        tags: ansible

      - name: Allow login on https port
        lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: "^(#\\s+|)Port "
            insertafter: "^(#\\s+|)Port "
            line: "Port 22\nPort 443"
        notify: Restart sshd
        tags: ansible

      - name: Change port in kube-apiserver
        lineinfile:
            dest: /etc/kubernetes/manifests/kube-apiserver.yaml
            regexp: '        - "--secure-port=443"'
            line: '        - "--secure-port=8443"'
        notify: Restart kubelet
        tags: ansible

  handlers:
      - name: Restart kubelet
        service:
            name: kubelet
            state: restarted

      - name: Restart sshd
        service:
            name: sshd
            state: restarted

- name: Install Ansible on ACS Master Nodes
  hosts: ~containerservice-adalab
  become: true
  vars:
      ansible_packages: ansible
      python_packages:
          - python-pip
          - python-dev
          - build-essential
  tasks:
      - name: Install Ansible PPA key
        apt_key:
            id: 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
            keyserver: keyserver.ubuntu.com
            state: present
        tags: ansible

      - name: Install Ansible PPA
        apt_repository:
            repo: 'ppa:ansible/ansible'
            state: present
        tags: ansible

      - name: Install Ansible packages
        apt:
            name: "{{ item }}"
            state: present
            update_cache: yes
        with_items: "{{ ansible_packages }}"
        tags: ansible

- name: Install ansible-container
  hosts: ~containerservice-adalab
  become: true
  vars:
      bleeding_edge: False
  tasks:
      - name: Downloads get-pip.py
        get_url:
          url: https://bootstrap.pypa.io/get-pip.py
          dest: /tmp/get-pip.py
        tags: ansible

      - name: Installs pip
        command: python /tmp/get-pip.py creates=/bin/pip2
        tags: ansible

      - name: Upgrade setuptools
        pip: name=setuptools state=latest
        tags: ansible

      - name: Get openshift-restclient-python
        git:
            repo: "https://github.com/openshift/openshift-restclient-python.git"
            dest: /var/tmp/openshift-restclient-python
            force: yes
        tags: ansible

      - name: Fix openshift-restclient-python version string
        lineinfile:
            dest: /var/tmp/openshift-restclient-python/setup.py
            regexp: '^CLIENT_VERSION = '
            line: 'CLIENT_VERSION = "1.0.0"'
        tags: ansible

      - name: Install openshift-restclient-python
        pip:
            name: /var/tmp/openshift-restclient-python
        tags: ansible

      - name: Installs ansible-container 0.9.0.0
        pip: name=ansible-container
        tags: ansible
        when: bleeding_edge

      - name: Install ansible-container 0.9.0.0 kubernetes and docker support
        # BUG: pip breaks here, as it translates command to: ansible-container[docker k8s]
        command: pip install ansible-container[docker,k8s]
        tags: ansible
        when: bleeding_edge

      - name: Installs ansible-container 0.3.0
        pip: name=ansible-container==0.3.0
        tags: ansible
        when: not bleeding_edge

- name: Install example repositories
  hosts: ~containerservice-adalab
  become: false
  tasks:
      - name: Install ansible-container-examples
        git:
            repo: "https://github.com/ansible/ansible-container-examples.git"
            dest: examples
        tags: examples

      - name: Install ansible-container-demo
        git:
            repo: "https://github.com/linuxpolska/ansible-container-demo.git"
            dest: slides
        tags: examples

